# Generated by Django 4.0.5 on 2022-11-01 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event',
            new_name='room',
        ),
    ]
